name: sa-with-ema

dependencies:
  - python=3.8.3
  - pip
  - matplotlib
  - seaborn
  - pandas
  - numpy
  - ipyparallel
  - scikit-learn
  - statsmodels
  - jupyterlab
  - pip:
    - ema_workbench
    - mesa
    - SALib